import capa1 from '../assets/910+GIdldiL.jpg'
import capa2 from '../assets/stephen-king-billy-summers-novo-livro-2021-lançamento.jpg'
import capa3 from '../assets/livro1.jpg'
import capa4 from '../assets/livro2.webp'
import capa5 from '../assets/livro3.jpg'
import capa6 from '../assets/livro4.jpg'

export const BookData = [
  {
    id: 1,
    livro: 'Donnie Darko',
    autor: 'Richard Kelly',
    ano: '2005',
    genero: 'Ficção',
    image: capa1,
    preco: 'R$ 9,90',
  },
  {
    id: 2,
    livro: 'Donnie Darko',
    autor: 'Richard Kelly',
    ano: '2005',
    genero: 'Ficção',
    image: capa2,
    preco: 'R$ 9,90',
  },
  {
    id: 3,
    livro: 'Donnie Darko',
    autor: 'Richard Kelly',
    ano: '2005',
    genero: 'Ficção',
    image: capa3,
    preco: 'R$ 9,90',
  },
  {
    id: 4,
    livro: 'Donnie Darko',
    autor: 'Richard Kelly',
    ano: '2005',
    genero: 'Ficção',
    image: capa4,
    preco: 'R$ 9,90',
  },
  {
    id: 5,
    livro: 'Donnie Darko',
    autor: 'Richard Kelly',
    ano: '2005',
    genero: 'Ficção',
    image: capa5,
    preco: 'R$ 9,90',
  },
  {
    id: 6,
    livro: 'Donnie Darko',
    autor: 'Richard Kelly',
    ano: '2005',
    genero: 'Ficção',
    image: capa6,
    preco: 'R$ 9,90',
  },
  {
    id: 7,
    livro: 'Donnie Darko',
    autor: 'Richard Kelly',
    ano: '2005',
    genero: 'Ficção',
    image: capa2,
    preco: 'R$ 9,90',
  },
  {
    id: 8,
    livro: 'Donnie Darko',
    autor: 'Richard Kelly',
    ano: '2005',
    genero: 'Ficção',
    image: capa4,
    preco: 'R$ 9,90',
  },
  {
    id: 9,
    livro: 'Donnie Darko',
    autor: 'Richard Kelly',
    ano: '2005',
    genero: 'Ficção',
    image: capa6,
    preco: 'R$ 9,90',
  },
  {
    id: 10,
    livro: 'Donnie Darko',
    autor: 'Richard Kelly',
    ano: '2005',
    genero: 'Ficção',
    image: capa2,
    preco: 'R$ 9,90',
  },
  {
    id: 11,
    livro: 'Donnie Darko',
    autor: 'Richard Kelly',
    ano: '2005',
    genero: 'Ficção',
    image: capa1,
    preco: 'R$ 9,90',
  },
  {
    id: 12,
    livro: 'Donnie Darko',
    autor: 'Richard Kelly',
    ano: '2005',
    genero: 'Ficção',
    image: capa3,
    preco: 'R$ 9,90',
  },
]
